# Generated by Django 5.2.7 on 2025-10-15 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semesters', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptorFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='descriptors/')),
                ('is_scanned', models.BooleanField(default=False)),
                ('text_cache', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descriptors', to='semesters.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptors', to='subjects.subject')),
            ],
            options={
                'unique_together': {('subject', 'semester')},
            },
        ),
    ]
