# Generated by Django 5.2.7 on 2025-11-26 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subjectphaseprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectphaseprogress',
            options={'ordering': ('subject', 'phase'), 'verbose_name': 'Progreso de fase', 'verbose_name_plural': 'Progresos de fase'},
        ),
        migrations.RemoveConstraint(
            model_name='subjectphaseprogress',
            name='unique_subject_phase',
        ),
        migrations.AlterField(
            model_name='subject',
            name='campus',
            field=models.CharField(default='Chillán', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectphaseprogress',
            name='phase',
            field=models.CharField(choices=[('formulacion', 'Formulación de requerimientos'), ('gestion', 'Gestión de requerimientos'), ('validacion', 'Validación de requerimientos')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='subjectphaseprogress',
            constraint=models.UniqueConstraint(fields=('subject', 'phase'), name='uniq_subject_phase_progress'),
        ),
    ]
